apiVersion: v1
kind: Pod
metadata:
  labels:
    app: proxy
  name: proxy

spec:
  nodeName: linux
  containers:
  - env:
    - name: TZ
      value: Europe/Berlin
    name: proxy
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
      hostPort: 80
    - containerPort: 443
      protocol: TCP
      hostPort: 443

    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/nginx/certs
      name: certs
    - mountPath: /tmp/docker.sock
      name: docker-socket
    - mountPath: /etc/nginx/nginx.conf
      name: nginx-config
    - mountPath: /var/log/nginx
      name: nginx-logs
  restartPolicy: Always
  volumes:
    - name: certs
      hostPath:
        path: "/home/<someFolderLocation>/certs-pv"
    - name: docker-socket
      hostPath:
        path: "/var/run/docker.sock"
        type: Socket
    - name: nginx-config
      hostPath:
        path: "/home/<someFolderLocation>/nginx.conf"
        type: File
    - name: nginx-logs
      hostPath:
        path: "/home/<someFolderLocation>/nginx-logs"
